package com.oceanx.freshcart.presentation.ordersuccess

import android.os.Bundle
import android.view.View
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs
import com.oceanx.freshcart.R
import com.oceanx.freshcart.databinding.FragmentOrderSuccessBinding
import com.oceanx.freshcart.utils.toCurrencyString
import com.oceanx.freshcart.utils.toast

/**
 * OrderSuccessFragment - displays order confirmation after successful placement.
 *
 * Features:
 * - Order ID display
 * - Bill total
 * - Delivery address and payment method summary
 * - Track Order button (placeholder)
 * - Continue Shopping button
 *
 * Receives order data via Safe Args from CheckoutFragment.
 */
class OrderSuccessFragment : Fragment(R.layout.fragment_order_success) {

    private var _binding: FragmentOrderSuccessBinding? = null
    private val binding get() = _binding!!

    /**
     * Safe Args — type-safe navigation arguments.
     * These are defined in nav_graph.xml and auto-generated by the Safe Args plugin.
     * Much safer than raw arguments?.getString("key") which can fail silently.
     */
    private val args: OrderSuccessFragmentArgs by navArgs()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        _binding = FragmentOrderSuccessBinding.bind(view)

        displayOrderDetails()
        setupButtons()
    }

    /**
     * Display order details from navigation arguments.
     */
    private fun displayOrderDetails() {
        binding.orderIdValue.text = args.orderId
        binding.totalAmountValue.text = args.totalAmount.toCurrencyString()
        binding.deliveryAddressValue.text = args.deliveryAddress
        binding.paymentMethodValue.text = args.paymentMethod
    }

    /**
     * Set up button click handlers.
     */
    private fun setupButtons() {
        binding.trackOrderButton.setOnClickListener {
            requireContext().toast(getString(R.string.order_tracking_message))
        }

        binding.continueShoppingButton.setOnClickListener {
            findNavController().navigate(
                R.id.action_orderSuccessFragment_to_homeFragment
            )
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}
